[package]
name = "tx-spamer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = "0.18.0"
futures = "0.3.15"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
hex = "0.4.3"